export const TYPES_ACTIONS = {
  SESSION: {
    SET_CLIENT_TYPE: "SET_CLIENT_TYPE",
    SET_USER_TYPE: "SET_USER_TYPE",
    CLOSE_USER_TYPE: "CLOSE_USER_TYPE",
    CLOSE_CLIENT_TYPE: "CLOSE_CLIENT_TYPE",
  },
  ALERT: {
    PUSH: "ALERT_PUSH",
    POP: "ALERT_POP",
    DELETE_ALL: "ALERT_DELETE",
  },
};
